[profile.default]
src = "packages/contracts/src"
test = "packages/contracts/test"
script = "packages/contracts/script"
out = "packages/contracts/out"
libs = ["packages/contracts/lib"]
viaIR = true
remappings = [
  "@ens-contracts=node_modules/@ensdomains/ens-contracts/contracts",
  "@ensdomains=node_modules/@ensdomains",
  "@openzeppelin=node_modules/@openzeppelin",
  "forge-std=node_modules/forge-std/src",
  "@eth-optimism/contracts-bedrock/src/libraries=packages/contracts/lib/optimism-bedrock-contracts",
  "@nitro-contracts=node_modules/@arbitrum/nitro-contracts",
  "@evmgateway=packages/contracts/src/evmgateway",
]
fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./packages/contracts/out" },
]
sparse_mode = true

ignored_warnings_from = [
  "node_modules/",
  "packages/contracts/node_modules/",
  "packages/contracts/lib/**",
  "**/src/evmgateway/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }


[rpc_endpoints]
sepolia = "${RPC_URL}"
arb_sepolia = "${L2_RPC_URL}"


[fmt]
line_length = 80
single_line_statement_blocks = "single"
multiline_func_header = "all"
contract_new_lines = true
